styleguide: plataformatec/linters
engines:

  ######################################
  ########## Static analyzers ##########
  ######################################

  # PHP
  phpmd:
    enabled: true
  phan:
    enabled: true

  # Ruby
  rubocop:
    enabled: true
  reek:
    enabled: true

  # Python
  radon:
    enabled: true

  # Elixir
  credo:
    enabled: true
  
  # Go
  govet:
    enabled: true

  # Swift
  tailor:
    enabled: true
  
  # C
  gnu-complexity:
    enabled: true

  ######################################
  ############## Formaters #############
  ######################################

  # Go
  gofmt:
    enabled: true

  ######################################
  ############### Linters ##############
  ######################################

  # Javascript
  eslint:
    enabled: true

  # Go
  golint:
    enabled: true
